export const typeColors = {
  Normal: ["#e5e0d4", "#ffffff"],
  Fire: ["#ff9c54", "#fff0d7"],
  Water: ["#66b8ff", "#e2f4ff"],
  Electric: ["#ffe15b", "#fff8cf"],
  Grass: ["#72d06b", "#e6ffdf"],
  Ice: ["#8be0ec", "#ebfbff"],
  Fighting: ["#d46b55", "#ffe6df"],
  Poison: ["#bc7ad6", "#f7e8ff"],
  Ground: ["#d5ab62", "#fff1d5"],
  Flying: ["#9db5ff", "#eef3ff"],
  Psychic: ["#ff84bc", "#ffeaf4"],
  Bug: ["#b7cf4f", "#f6ffd8"],
  Rock: ["#b9a36a", "#f6efd8"],
  Ghost: ["#8370bf", "#eee9ff"],
  Dragon: ["#8267ff", "#eeeaff"],
  Dark: ["#75685f", "#ece7e3"],
  Steel: ["#aeb8c8", "#f0f4fa"],
  Fairy: ["#ff9bd1", "#fff0f8"]
};

const attackNames = {
  Normal: ["Quick Strike", "Comet Slam"],
  Fire: ["Ember Shot", "Inferno Burst"],
  Water: ["Aqua Jab", "Tidal Crash"],
  Electric: ["Spark", "Thunder Rail"],
  Grass: ["Vine Lash", "Solar Bloom"],
  Ice: ["Frost Clip", "Blizzard Edge"],
  Fighting: ["Knuckle Jab", "Impact Throw"],
  Poison: ["Toxic Sting", "Venom Wave"],
  Ground: ["Mud Shot", "Quake Break"],
  Flying: ["Wing Cut", "Sky Dive"],
  Psychic: ["Mind Tap", "Psy Surge"],
  Bug: ["Needle Tap", "Swarm Rush"],
  Rock: ["Stone Chip", "Boulder Crush"],
  Ghost: ["Shade Touch", "Night Spiral"],
  Dragon: ["Scale Hit", "Dragon Roar"],
  Dark: ["Sneak Bite", "Blackout"],
  Steel: ["Metal Flick", "Iron Drive"],
  Fairy: ["Charm Pop", "Moon Gleam"]
};

const pokemonDataset = [
  {
    id: 1,
    name: "Bulbasaur",
    types: ["Grass", "Poison"],
    hp: 70,
    attack: 48,
    defense: 52,
    speed: 45,
    rarity: "Common",
    description: "A dependable seed Pokemon that stores energy in the bulb on its back.",
    evolutionStage: "Basic",
    weakness: "Fire",
    ability: "Overgrow"
  },
  {
    id: 2,
    name: "Ivysaur",
    types: ["Grass", "Poison"],
    hp: 88,
    attack: 62,
    defense: 66,
    speed: 56,
    rarity: "Uncommon",
    description: "Its blooming bud releases a sweet scent before a powerful solar strike.",
    evolutionStage: "Stage 1",
    weakness: "Fire",
    ability: "Solar Charge"
  },
  {
    id: 3,
    name: "Venusaur",
    types: ["Grass", "Poison"],
    hp: 128,
    attack: 84,
    defense: 88,
    speed: 64,
    rarity: "Rare",
    description: "The flower on its back gathers sunlight to fuel heavy grass attacks.",
    evolutionStage: "Stage 2",
    weakness: "Fire",
    ability: "Jungle Bloom"
  },
  {
    id: 4,
    name: "Charmander",
    types: ["Fire"],
    hp: 64,
    attack: 56,
    defense: 44,
    speed: 60,
    rarity: "Common",
    description: "The flame on its tail burns brighter when it is ready to battle.",
    evolutionStage: "Basic",
    weakness: "Water",
    ability: "Blaze"
  },
  {
    id: 5,
    name: "Charmeleon",
    types: ["Fire"],
    hp: 86,
    attack: 72,
    defense: 58,
    speed: 72,
    rarity: "Uncommon",
    description: "A fierce fighter that swings its tail flame to intimidate opponents.",
    evolutionStage: "Stage 1",
    weakness: "Water",
    ability: "Flare Temper"
  },
  {
    id: 6,
    name: "Charizard",
    types: ["Fire", "Flying"],
    hp: 138,
    attack: 96,
    defense: 82,
    speed: 92,
    rarity: "Holo Rare",
    description: "It soars through the sky and blasts intense fire from above.",
    evolutionStage: "Stage 2",
    weakness: "Water",
    ability: "Inferno Wings"
  },
  {
    id: 7,
    name: "Squirtle",
    types: ["Water"],
    hp: 68,
    attack: 48,
    defense: 64,
    speed: 43,
    rarity: "Common",
    description: "It withdraws into its shell before countering with pressurized water.",
    evolutionStage: "Basic",
    weakness: "Electric",
    ability: "Torrent"
  },
  {
    id: 8,
    name: "Wartortle",
    types: ["Water"],
    hp: 88,
    attack: 64,
    defense: 78,
    speed: 58,
    rarity: "Uncommon",
    description: "Its fluffy tail helps it balance during fast aquatic movement.",
    evolutionStage: "Stage 1",
    weakness: "Electric",
    ability: "Shell Guard"
  },
  {
    id: 9,
    name: "Blastoise",
    types: ["Water"],
    hp: 136,
    attack: 88,
    defense: 100,
    speed: 72,
    rarity: "Rare",
    description: "Water cannons on its shell fire with enough force to break stone.",
    evolutionStage: "Stage 2",
    weakness: "Electric",
    ability: "Hydro Cannon"
  },
  {
    id: 12,
    name: "Butterfree",
    types: ["Bug", "Flying"],
    hp: 78,
    attack: 52,
    defense: 58,
    speed: 76,
    rarity: "Uncommon",
    description: "Its wings scatter sparkling powder that can disorient attackers.",
    evolutionStage: "Stage 2",
    weakness: "Fire",
    ability: "Compound Eyes"
  },
  {
    id: 15,
    name: "Beedrill",
    types: ["Bug", "Poison"],
    hp: 82,
    attack: 86,
    defense: 52,
    speed: 82,
    rarity: "Uncommon",
    description: "It darts forward in a blur and strikes with poisonous stingers.",
    evolutionStage: "Stage 2",
    weakness: "Fire",
    ability: "Swarm"
  },
  {
    id: 18,
    name: "Pidgeot",
    types: ["Normal", "Flying"],
    hp: 104,
    attack: 78,
    defense: 72,
    speed: 96,
    rarity: "Rare",
    description: "With powerful wings, it creates gusts that can bend tall trees.",
    evolutionStage: "Stage 2",
    weakness: "Electric",
    ability: "Keen Eye"
  },
  {
    id: 25,
    name: "Pikachu",
    types: ["Electric"],
    hp: 72,
    attack: 64,
    defense: 48,
    speed: 98,
    rarity: "Rare",
    description: "Electricity builds in its cheeks before it releases a quick shock.",
    evolutionStage: "Basic",
    weakness: "Ground",
    ability: "Static"
  },
  {
    id: 26,
    name: "Raichu",
    types: ["Electric"],
    hp: 98,
    attack: 88,
    defense: 64,
    speed: 110,
    rarity: "Rare",
    description: "It channels stored electricity through its tail to stay grounded.",
    evolutionStage: "Stage 1",
    weakness: "Ground",
    ability: "Surge Surfer"
  },
  {
    id: 31,
    name: "Nidoqueen",
    types: ["Poison", "Ground"],
    hp: 128,
    attack: 82,
    defense: 94,
    speed: 72,
    rarity: "Rare",
    description: "Armored scales and fierce loyalty make it a resilient team anchor.",
    evolutionStage: "Stage 2",
    weakness: "Water",
    ability: "Poison Point"
  },
  {
    id: 34,
    name: "Nidoking",
    types: ["Poison", "Ground"],
    hp: 124,
    attack: 96,
    defense: 82,
    speed: 80,
    rarity: "Rare",
    description: "Its horn and heavy tail let it smash through tough defenses.",
    evolutionStage: "Stage 2",
    weakness: "Water",
    ability: "Sheer Force"
  },
  {
    id: 35,
    name: "Clefairy",
    types: ["Fairy"],
    hp: 86,
    attack: 48,
    defense: 56,
    speed: 42,
    rarity: "Uncommon",
    description: "A moonlit Pokemon said to gather where falling stars land.",
    evolutionStage: "Basic",
    weakness: "Poison",
    ability: "Cute Charm"
  },
  {
    id: 38,
    name: "Ninetales",
    types: ["Fire"],
    hp: 106,
    attack: 82,
    defense: 78,
    speed: 106,
    rarity: "Rare",
    description: "Its nine tails shimmer with a mysterious flame-like energy.",
    evolutionStage: "Stage 1",
    weakness: "Water",
    ability: "Flash Fire"
  },
  {
    id: 39,
    name: "Jigglypuff",
    types: ["Normal", "Fairy"],
    hp: 98,
    attack: 44,
    defense: 42,
    speed: 38,
    rarity: "Common",
    description: "Its round body and soothing song can lull rivals into mistakes.",
    evolutionStage: "Basic",
    weakness: "Steel",
    ability: "Cute Charm"
  },
  {
    id: 45,
    name: "Vileplume",
    types: ["Grass", "Poison"],
    hp: 112,
    attack: 78,
    defense: 86,
    speed: 54,
    rarity: "Rare",
    description: "Its huge petals release clouds of pollen during battle.",
    evolutionStage: "Stage 2",
    weakness: "Fire",
    ability: "Effect Spore"
  },
  {
    id: 52,
    name: "Meowth",
    types: ["Normal"],
    hp: 64,
    attack: 52,
    defense: 42,
    speed: 90,
    rarity: "Common",
    description: "A crafty Pokemon that loves shiny coins and quick strikes.",
    evolutionStage: "Basic",
    weakness: "Fighting",
    ability: "Pickup"
  },
  {
    id: 54,
    name: "Psyduck",
    types: ["Water"],
    hp: 76,
    attack: 54,
    defense: 52,
    speed: 56,
    rarity: "Common",
    description: "When its headache peaks, it unleashes unexpected psychic power.",
    evolutionStage: "Basic",
    weakness: "Electric",
    ability: "Cloud Nine"
  },
  {
    id: 59,
    name: "Arcanine",
    types: ["Fire"],
    hp: 124,
    attack: 104,
    defense: 84,
    speed: 96,
    rarity: "Rare",
    description: "A noble Pokemon known for its speed, loyalty, and blazing charge.",
    evolutionStage: "Stage 1",
    weakness: "Water",
    ability: "Intimidate"
  },
  {
    id: 62,
    name: "Poliwrath",
    types: ["Water", "Fighting"],
    hp: 118,
    attack: 86,
    defense: 94,
    speed: 72,
    rarity: "Rare",
    description: "Its trained muscles let it swim fast and punch even harder.",
    evolutionStage: "Stage 2",
    weakness: "Electric",
    ability: "Water Absorb"
  },
  {
    id: 65,
    name: "Alakazam",
    types: ["Psychic"],
    hp: 96,
    attack: 58,
    defense: 64,
    speed: 112,
    rarity: "Holo Rare",
    description: "A master of psychic attacks with a mind sharper than any blade.",
    evolutionStage: "Stage 2",
    weakness: "Dark",
    ability: "Synchronize"
  },
  {
    id: 68,
    name: "Machamp",
    types: ["Fighting"],
    hp: 130,
    attack: 110,
    defense: 88,
    speed: 66,
    rarity: "Rare",
    description: "Its four arms can throw rapid punches from every angle.",
    evolutionStage: "Stage 2",
    weakness: "Psychic",
    ability: "Guts"
  },
  {
    id: 76,
    name: "Golem",
    types: ["Rock", "Ground"],
    hp: 128,
    attack: 102,
    defense: 118,
    speed: 48,
    rarity: "Rare",
    description: "It rolls down mountains with enough force to shake the ground.",
    evolutionStage: "Stage 2",
    weakness: "Water",
    ability: "Sturdy"
  },
  {
    id: 78,
    name: "Rapidash",
    types: ["Fire"],
    hp: 98,
    attack: 90,
    defense: 72,
    speed: 112,
    rarity: "Uncommon",
    description: "Its fiery mane trails behind it as it races across open fields.",
    evolutionStage: "Stage 1",
    weakness: "Water",
    ability: "Run Away"
  },
  {
    id: 80,
    name: "Slowbro",
    types: ["Water", "Psychic"],
    hp: 124,
    attack: 78,
    defense: 104,
    speed: 34,
    rarity: "Rare",
    description: "Calm and durable, it absorbs hits before answering with psychic force.",
    evolutionStage: "Stage 1",
    weakness: "Electric",
    ability: "Regenerator"
  },
  {
    id: 82,
    name: "Magneton",
    types: ["Electric", "Steel"],
    hp: 94,
    attack: 74,
    defense: 90,
    speed: 78,
    rarity: "Uncommon",
    description: "A linked trio that releases magnetic pulses and crackling sparks.",
    evolutionStage: "Stage 1",
    weakness: "Ground",
    ability: "Magnet Pull"
  },
  {
    id: 87,
    name: "Dewgong",
    types: ["Water", "Ice"],
    hp: 108,
    attack: 70,
    defense: 82,
    speed: 70,
    rarity: "Uncommon",
    description: "It glides through cold water and freezes foes with icy breath.",
    evolutionStage: "Stage 1",
    weakness: "Electric",
    ability: "Thick Fat"
  },
  {
    id: 89,
    name: "Muk",
    types: ["Poison"],
    hp: 116,
    attack: 92,
    defense: 78,
    speed: 50,
    rarity: "Uncommon",
    description: "Its sludge body spreads toxic pressure across the battlefield.",
    evolutionStage: "Stage 1",
    weakness: "Ground",
    ability: "Poison Touch"
  },
  {
    id: 91,
    name: "Cloyster",
    types: ["Water", "Ice"],
    hp: 96,
    attack: 88,
    defense: 124,
    speed: 70,
    rarity: "Rare",
    description: "A fortress-like shell protects it while it fires icy spikes.",
    evolutionStage: "Stage 1",
    weakness: "Electric",
    ability: "Skill Link"
  },
  {
    id: 94,
    name: "Gengar",
    types: ["Ghost", "Poison"],
    hp: 108,
    attack: 72,
    defense: 70,
    speed: 116,
    rarity: "Holo Rare",
    description: "It slips through shadows and strikes with eerie ghostly energy.",
    evolutionStage: "Stage 2",
    weakness: "Dark",
    ability: "Cursed Body"
  },
  {
    id: 95,
    name: "Onix",
    types: ["Rock", "Ground"],
    hp: 96,
    attack: 70,
    defense: 126,
    speed: 76,
    rarity: "Uncommon",
    description: "Its massive stone body tunnels through earth at surprising speed.",
    evolutionStage: "Basic",
    weakness: "Water",
    ability: "Rock Head"
  },
  {
    id: 103,
    name: "Exeggutor",
    types: ["Grass", "Psychic"],
    hp: 118,
    attack: 92,
    defense: 82,
    speed: 54,
    rarity: "Rare",
    description: "Its three heads think together to launch strange psychic attacks.",
    evolutionStage: "Stage 1",
    weakness: "Fire",
    ability: "Harvest"
  },
  {
    id: 105,
    name: "Marowak",
    types: ["Ground"],
    hp: 98,
    attack: 86,
    defense: 98,
    speed: 54,
    rarity: "Uncommon",
    description: "It wields a bone club with practiced timing and fierce focus.",
    evolutionStage: "Stage 1",
    weakness: "Water",
    ability: "Battle Armor"
  },
  {
    id: 113,
    name: "Chansey",
    types: ["Normal"],
    hp: 150,
    attack: 28,
    defense: 42,
    speed: 52,
    rarity: "Rare",
    description: "Its gentle nature and high stamina make it excellent support.",
    evolutionStage: "Basic",
    weakness: "Fighting",
    ability: "Natural Cure"
  },
  {
    id: 121,
    name: "Starmie",
    types: ["Water", "Psychic"],
    hp: 96,
    attack: 82,
    defense: 82,
    speed: 112,
    rarity: "Rare",
    description: "Its glowing core spins as it launches precise psychic waves.",
    evolutionStage: "Stage 1",
    weakness: "Electric",
    ability: "Illuminate"
  },
  {
    id: 123,
    name: "Scyther",
    types: ["Bug", "Flying"],
    hp: 102,
    attack: 102,
    defense: 78,
    speed: 112,
    rarity: "Rare",
    description: "It moves like a green blur and cuts with scythe-like arms.",
    evolutionStage: "Basic",
    weakness: "Fire",
    ability: "Technician"
  },
  {
    id: 130,
    name: "Gyarados",
    types: ["Water", "Flying"],
    hp: 136,
    attack: 118,
    defense: 86,
    speed: 82,
    rarity: "Holo Rare",
    description: "A furious sea serpent that overwhelms foes with raw power.",
    evolutionStage: "Stage 1",
    weakness: "Electric",
    ability: "Intimidate"
  },
  {
    id: 131,
    name: "Lapras",
    types: ["Water", "Ice"],
    hp: 132,
    attack: 82,
    defense: 86,
    speed: 66,
    rarity: "Rare",
    description: "A gentle swimmer with icy songs and sturdy defensive power.",
    evolutionStage: "Basic",
    weakness: "Electric",
    ability: "Water Absorb"
  },
  {
    id: 133,
    name: "Eevee",
    types: ["Normal"],
    hp: 74,
    attack: 58,
    defense: 54,
    speed: 64,
    rarity: "Common",
    description: "Its unstable genetic makeup lets it evolve in many directions.",
    evolutionStage: "Basic",
    weakness: "Fighting",
    ability: "Adaptability"
  },
  {
    id: 134,
    name: "Vaporeon",
    types: ["Water"],
    hp: 128,
    attack: 78,
    defense: 82,
    speed: 66,
    rarity: "Rare",
    description: "Its body can blend with water before striking from the current.",
    evolutionStage: "Stage 1",
    weakness: "Electric",
    ability: "Water Absorb"
  },
  {
    id: 135,
    name: "Jolteon",
    types: ["Electric"],
    hp: 92,
    attack: 84,
    defense: 72,
    speed: 122,
    rarity: "Rare",
    description: "Its charged fur bristles before releasing sharp electric bursts.",
    evolutionStage: "Stage 1",
    weakness: "Ground",
    ability: "Volt Absorb"
  },
  {
    id: 136,
    name: "Flareon",
    types: ["Fire"],
    hp: 102,
    attack: 112,
    defense: 74,
    speed: 72,
    rarity: "Rare",
    description: "It stores heat in its fluffy coat and releases scorching flames.",
    evolutionStage: "Stage 1",
    weakness: "Water",
    ability: "Flash Fire"
  },
  {
    id: 143,
    name: "Snorlax",
    types: ["Normal"],
    hp: 160,
    attack: 106,
    defense: 92,
    speed: 32,
    rarity: "Holo Rare",
    description: "A massive Pokemon that shrugs off hits and counters with heavy force.",
    evolutionStage: "Basic",
    weakness: "Fighting",
    ability: "Thick Fat"
  },
  {
    id: 144,
    name: "Articuno",
    types: ["Ice", "Flying"],
    hp: 122,
    attack: 88,
    defense: 100,
    speed: 88,
    rarity: "Legendary",
    description: "This legendary bird freezes the air with every elegant wingbeat.",
    evolutionStage: "Legendary",
    weakness: "Rock",
    ability: "Pressure"
  },
  {
    id: 145,
    name: "Zapdos",
    types: ["Electric", "Flying"],
    hp: 122,
    attack: 96,
    defense: 88,
    speed: 100,
    rarity: "Legendary",
    description: "A legendary bird that appears with thunderclouds and bright sparks.",
    evolutionStage: "Legendary",
    weakness: "Rock",
    ability: "Static"
  },
  {
    id: 146,
    name: "Moltres",
    types: ["Fire", "Flying"],
    hp: 122,
    attack: 100,
    defense: 88,
    speed: 96,
    rarity: "Legendary",
    description: "Its fiery wings leave trails of flame across the sky.",
    evolutionStage: "Legendary",
    weakness: "Rock",
    ability: "Flame Body"
  },
  {
    id: 149,
    name: "Dragonite",
    types: ["Dragon", "Flying"],
    hp: 146,
    attack: 124,
    defense: 98,
    speed: 86,
    rarity: "Holo Rare",
    description: "A kindhearted dragon with enough power to circle the globe.",
    evolutionStage: "Stage 2",
    weakness: "Ice",
    ability: "Inner Focus"
  },
  {
    id: 150,
    name: "Mewtwo",
    types: ["Psychic"],
    hp: 148,
    attack: 112,
    defense: 96,
    speed: 124,
    rarity: "Legendary",
    description: "A genetically engineered Pokemon with overwhelming psychic power.",
    evolutionStage: "Legendary",
    weakness: "Dark",
    ability: "Pressure"
  },
  {
    id: 151,
    name: "Mew",
    types: ["Psychic"],
    hp: 126,
    attack: 92,
    defense: 92,
    speed: 108,
    rarity: "Mythic",
    description: "A mythical Pokemon said to contain the genetic code of all Pokemon.",
    evolutionStage: "Mythic",
    weakness: "Dark",
    ability: "Synchronize"
  },
  {
    id: 154,
    name: "Meganium",
    types: ["Grass"],
    hp: 124,
    attack: 82,
    defense: 100,
    speed: 78,
    rarity: "Rare",
    description: "The aroma from its petals can calm aggression during battle.",
    evolutionStage: "Stage 2",
    weakness: "Fire",
    ability: "Leaf Guard"
  },
  {
    id: 157,
    name: "Typhlosion",
    types: ["Fire"],
    hp: 126,
    attack: 96,
    defense: 84,
    speed: 100,
    rarity: "Rare",
    description: "It creates explosive heat waves when its flames flare up.",
    evolutionStage: "Stage 2",
    weakness: "Water",
    ability: "Blaze"
  },
  {
    id: 160,
    name: "Feraligatr",
    types: ["Water"],
    hp: 130,
    attack: 104,
    defense: 96,
    speed: 78,
    rarity: "Rare",
    description: "It lunges forward with crushing jaws and unstoppable momentum.",
    evolutionStage: "Stage 2",
    weakness: "Electric",
    ability: "Torrent"
  },
  {
    id: 181,
    name: "Ampharos",
    types: ["Electric"],
    hp: 116,
    attack: 88,
    defense: 86,
    speed: 64,
    rarity: "Rare",
    description: "Its tail shines like a beacon and stores steady electric power.",
    evolutionStage: "Stage 2",
    weakness: "Ground",
    ability: "Static"
  },
  {
    id: 196,
    name: "Espeon",
    types: ["Psychic"],
    hp: 96,
    attack: 76,
    defense: 74,
    speed: 116,
    rarity: "Rare",
    description: "It reads air currents and enemy intent with its sensitive fur.",
    evolutionStage: "Stage 1",
    weakness: "Dark",
    ability: "Magic Bounce"
  },
  {
    id: 197,
    name: "Umbreon",
    types: ["Dark"],
    hp: 112,
    attack: 74,
    defense: 104,
    speed: 76,
    rarity: "Rare",
    description: "Its rings glow in darkness before it launches a patient counterattack.",
    evolutionStage: "Stage 1",
    weakness: "Fighting",
    ability: "Synchronize"
  },
  {
    id: 208,
    name: "Steelix",
    types: ["Steel", "Ground"],
    hp: 128,
    attack: 96,
    defense: 138,
    speed: 42,
    rarity: "Rare",
    description: "A hardened steel serpent that tunnels deeper than Onix ever could.",
    evolutionStage: "Stage 1",
    weakness: "Fire",
    ability: "Sturdy"
  },
  {
    id: 212,
    name: "Scizor",
    types: ["Bug", "Steel"],
    hp: 112,
    attack: 116,
    defense: 104,
    speed: 70,
    rarity: "Holo Rare",
    description: "Its steel claws strike quickly and look heavier than they feel.",
    evolutionStage: "Stage 1",
    weakness: "Fire",
    ability: "Technician"
  },
  {
    id: 248,
    name: "Tyranitar",
    types: ["Rock", "Dark"],
    hp: 148,
    attack: 126,
    defense: 116,
    speed: 72,
    rarity: "Holo Rare",
    description: "An armored powerhouse that can change the shape of mountains.",
    evolutionStage: "Stage 2",
    weakness: "Fighting",
    ability: "Sand Stream"
  },
  {
    id: 254,
    name: "Sceptile",
    types: ["Grass"],
    hp: 118,
    attack: 104,
    defense: 78,
    speed: 120,
    rarity: "Rare",
    description: "Leaf blades on its arms slash with precise jungle speed.",
    evolutionStage: "Stage 2",
    weakness: "Fire",
    ability: "Overgrow"
  },
  {
    id: 257,
    name: "Blaziken",
    types: ["Fire", "Fighting"],
    hp: 126,
    attack: 118,
    defense: 82,
    speed: 92,
    rarity: "Holo Rare",
    description: "It leaps high and lands blazing kicks with explosive force.",
    evolutionStage: "Stage 2",
    weakness: "Water",
    ability: "Speed Boost"
  },
  {
    id: 260,
    name: "Swampert",
    types: ["Water", "Ground"],
    hp: 138,
    attack: 112,
    defense: 100,
    speed: 72,
    rarity: "Rare",
    description: "Powerful arms let it swim through rough water and move boulders.",
    evolutionStage: "Stage 2",
    weakness: "Grass",
    ability: "Torrent"
  },
  {
    id: 282,
    name: "Gardevoir",
    types: ["Psychic", "Fairy"],
    hp: 112,
    attack: 84,
    defense: 82,
    speed: 92,
    rarity: "Rare",
    description: "It protects trusted trainers with elegant psychic force.",
    evolutionStage: "Stage 2",
    weakness: "Steel",
    ability: "Trace"
  },
  {
    id: 302,
    name: "Sableye",
    types: ["Dark", "Ghost"],
    hp: 82,
    attack: 78,
    defense: 86,
    speed: 52,
    rarity: "Uncommon",
    description: "It lurks in caves and uses gem-like eyes to unsettle enemies.",
    evolutionStage: "Basic",
    weakness: "Fairy",
    ability: "Prankster"
  },
  {
    id: 306,
    name: "Aggron",
    types: ["Steel", "Rock"],
    hp: 132,
    attack: 110,
    defense: 132,
    speed: 54,
    rarity: "Rare",
    description: "A territorial armored Pokemon that defends mountains with force.",
    evolutionStage: "Stage 2",
    weakness: "Fighting",
    ability: "Rock Head"
  },
  {
    id: 330,
    name: "Flygon",
    types: ["Ground", "Dragon"],
    hp: 118,
    attack: 100,
    defense: 86,
    speed: 108,
    rarity: "Rare",
    description: "Its wings stir desert sand into a veil around its attacks.",
    evolutionStage: "Stage 2",
    weakness: "Ice",
    ability: "Levitate"
  },
  {
    id: 350,
    name: "Milotic",
    types: ["Water"],
    hp: 126,
    attack: 76,
    defense: 98,
    speed: 88,
    rarity: "Rare",
    description: "A graceful Pokemon whose calm presence can steady an entire team.",
    evolutionStage: "Stage 1",
    weakness: "Electric",
    ability: "Marvel Scale"
  },
  {
    id: 359,
    name: "Absol",
    types: ["Dark"],
    hp: 96,
    attack: 116,
    defense: 72,
    speed: 92,
    rarity: "Rare",
    description: "It appears before disasters and strikes with sudden dark power.",
    evolutionStage: "Basic",
    weakness: "Fighting",
    ability: "Super Luck"
  },
  {
    id: 373,
    name: "Salamence",
    types: ["Dragon", "Flying"],
    hp: 140,
    attack: 128,
    defense: 92,
    speed: 104,
    rarity: "Holo Rare",
    description: "A dragon that finally gained wings and now battles with joy.",
    evolutionStage: "Stage 2",
    weakness: "Ice",
    ability: "Intimidate"
  },
  {
    id: 376,
    name: "Metagross",
    types: ["Steel", "Psychic"],
    hp: 138,
    attack: 124,
    defense: 126,
    speed: 72,
    rarity: "Holo Rare",
    description: "Four brains coordinate its heavy body with machine-like precision.",
    evolutionStage: "Stage 2",
    weakness: "Fire",
    ability: "Clear Body"
  },
  {
    id: 384,
    name: "Rayquaza",
    types: ["Dragon", "Flying"],
    hp: 154,
    attack: 136,
    defense: 98,
    speed: 116,
    rarity: "Legendary",
    description: "A sky-dwelling legend that descends with overwhelming dragon power.",
    evolutionStage: "Legendary",
    weakness: "Ice",
    ability: "Air Lock"
  },
  {
    id: 389,
    name: "Torterra",
    types: ["Grass", "Ground"],
    hp: 140,
    attack: 112,
    defense: 114,
    speed: 56,
    rarity: "Rare",
    description: "A walking grove whose heavy shell anchors powerful ground attacks.",
    evolutionStage: "Stage 2",
    weakness: "Ice",
    ability: "Overgrow"
  },
  {
    id: 392,
    name: "Infernape",
    types: ["Fire", "Fighting"],
    hp: 120,
    attack: 108,
    defense: 82,
    speed: 116,
    rarity: "Rare",
    description: "It mixes nimble martial arts with roaring flames.",
    evolutionStage: "Stage 2",
    weakness: "Water",
    ability: "Iron Fist"
  },
  {
    id: 395,
    name: "Empoleon",
    types: ["Water", "Steel"],
    hp: 126,
    attack: 98,
    defense: 106,
    speed: 72,
    rarity: "Rare",
    description: "Steel-edged wings and royal poise make it a durable attacker.",
    evolutionStage: "Stage 2",
    weakness: "Electric",
    ability: "Torrent"
  },
  {
    id: 445,
    name: "Garchomp",
    types: ["Dragon", "Ground"],
    hp: 144,
    attack: 130,
    defense: 104,
    speed: 110,
    rarity: "Holo Rare",
    description: "It tears across the ground and air like a living jet.",
    evolutionStage: "Stage 2",
    weakness: "Ice",
    ability: "Rough Skin"
  },
  {
    id: 448,
    name: "Lucario",
    types: ["Fighting", "Steel"],
    hp: 112,
    attack: 112,
    defense: 84,
    speed: 98,
    rarity: "Holo Rare",
    description: "It senses aura and shapes that energy into precise combat strikes.",
    evolutionStage: "Stage 1",
    weakness: "Fire",
    ability: "Inner Focus"
  },
  {
    id: 470,
    name: "Leafeon",
    types: ["Grass"],
    hp: 102,
    attack: 94,
    defense: 104,
    speed: 94,
    rarity: "Rare",
    description: "Its leaf-like body stays fresh in sunlight and cuts cleanly.",
    evolutionStage: "Stage 1",
    weakness: "Fire",
    ability: "Leaf Guard"
  },
  {
    id: 471,
    name: "Glaceon",
    types: ["Ice"],
    hp: 102,
    attack: 88,
    defense: 104,
    speed: 78,
    rarity: "Rare",
    description: "It lowers the air temperature to create glittering ice crystals.",
    evolutionStage: "Stage 1",
    weakness: "Fighting",
    ability: "Snow Cloak"
  },
  {
    id: 497,
    name: "Serperior",
    types: ["Grass"],
    hp: 118,
    attack: 88,
    defense: 100,
    speed: 114,
    rarity: "Rare",
    description: "Regal and swift, it pressures rivals with piercing confidence.",
    evolutionStage: "Stage 2",
    weakness: "Fire",
    ability: "Contrary"
  },
  {
    id: 500,
    name: "Emboar",
    types: ["Fire", "Fighting"],
    hp: 144,
    attack: 120,
    defense: 86,
    speed: 62,
    rarity: "Rare",
    description: "It charges with wrestling power and a blazing beard of fire.",
    evolutionStage: "Stage 2",
    weakness: "Water",
    ability: "Reckless"
  },
  {
    id: 503,
    name: "Samurott",
    types: ["Water"],
    hp: 126,
    attack: 108,
    defense: 92,
    speed: 76,
    rarity: "Rare",
    description: "A disciplined fighter that draws shell blades in a flash.",
    evolutionStage: "Stage 2",
    weakness: "Electric",
    ability: "Torrent"
  },
  {
    id: 571,
    name: "Zoroark",
    types: ["Dark"],
    hp: 104,
    attack: 112,
    defense: 72,
    speed: 106,
    rarity: "Rare",
    description: "It creates illusions to mislead foes before striking from hiding.",
    evolutionStage: "Stage 1",
    weakness: "Fighting",
    ability: "Illusion"
  },
  {
    id: 612,
    name: "Haxorus",
    types: ["Dragon"],
    hp: 128,
    attack: 134,
    defense: 96,
    speed: 98,
    rarity: "Holo Rare",
    description: "Its tusks can cleave steel and its battle focus rarely breaks.",
    evolutionStage: "Stage 2",
    weakness: "Ice",
    ability: "Mold Breaker"
  },
  {
    id: 635,
    name: "Hydreigon",
    types: ["Dark", "Dragon"],
    hp: 140,
    attack: 128,
    defense: 92,
    speed: 98,
    rarity: "Holo Rare",
    description: "A ruthless three-headed dragon that attacks anything it sees.",
    evolutionStage: "Stage 2",
    weakness: "Fairy",
    ability: "Levitate"
  },
  {
    id: 658,
    name: "Greninja",
    types: ["Water", "Dark"],
    hp: 118,
    attack: 112,
    defense: 78,
    speed: 126,
    rarity: "Holo Rare",
    description: "A swift ninja Pokemon that shapes water into cutting stars.",
    evolutionStage: "Stage 2",
    weakness: "Electric",
    ability: "Battle Bond"
  },
  {
    id: 700,
    name: "Sylveon",
    types: ["Fairy"],
    hp: 112,
    attack: 78,
    defense: 86,
    speed: 76,
    rarity: "Rare",
    description: "Ribbon-like feelers calm allies and soften enemy aggression.",
    evolutionStage: "Stage 1",
    weakness: "Steel",
    ability: "Pixilate"
  }
];

const excludedFromDeck = new Set([2, 5, 8, 15, 31, 35, 39, 45, 78, 87, 89, 91, 103, 105]);

export const pokemon = pokemonDataset.filter(mon => !excludedFromDeck.has(mon.id)).map(mon => {
  const [light, pale] = typeColors[mon.types[0]] || typeColors.Normal;
  const names = attackNames[mon.types[0]] || attackNames.Normal;

  return {
    ...mon,
    image: `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${mon.id}.png`,
    retreat: 1 + (mon.defense >= 95 ? 1 : 0) + (mon.speed <= 55 ? 1 : 0),
    cardBg: `linear-gradient(150deg, ${light}, ${pale} 62%, #ffffff)`,
    attacks: [
      { name: names[0], cost: 1, damage: Math.max(20, Math.round(mon.attack * 0.55 / 10) * 10) },
      { name: names[1], cost: 2, damage: Math.max(40, Math.round((mon.attack * 0.90 + 8) / 10) * 10) }
    ]
  };
});
